### ISSUE TITLE
Missing Project for Load balancer

### ISSUE THREAD

**Issue by LondheShubham153** [TrainWithShubham/90DaysOfDevOps#198]
As a part of 10 day 10 Projects I need a project on Load balancer with Terraform

**Comment by AbhipreyaGhosh** [comment]
Sir can i resolve this issue , if this is still open ? I have enrolled in batch 4 of devops with you , so before that i learned git and wanted to apply some inhand practices.

**Comment by LondheShubham153** [comment]
that's great @AbhipreyaGhosh 
you can give it a try

**Comment by chandangowdaS** [comment]
I will also try to implement load balancer using terraform and I have hands on experience and created ec2 instance using terraform
