### ISSUE TITLE
batch 4 link  should be updated in home page.

### ISSUE THREAD

**Issue by 0xPratyush** [TrainWithShubham/90DaysOfDevOps#218]
The link currently throwing to an 404 error page

**Comment by LondheShubham153** [comment]
Added the required change @0xPratyush

**Comment by 0xPratyush** [comment]
Thanks @LondheShubham153 bhai

**Comment by jeevith1996** [comment]
can you please show us the pushed codes in the git hub.
UseCase:
1.  we changed the url & pushed the changes to the github repository, but the changes are not shown inside github.
