### ISSUE TITLE
in Day6 Readme....first link for notes about permission in point1 is not working

### ISSUE THREAD

**Issue by sidharthhhh** [TrainWithShubham/90DaysOfDevOps#243]
link:- https://github.com/LondheShubham153/90DaysOfDevOps/tree/master/2023/day6/notes

just check day6 readme point no. 1 link , apart from this notes folder is working fine.

**Comment by kelvinparmar** [comment]
@shubhamlondhe1996 this is issue is right nots are not opening

**Comment by VikasDz** [comment]
> @shubhamlondhe1996 this is issue is right nots are not opening

You Have To Download The Repo to Open Notes the Format of is .doc Thats Why
